server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的id，没有限定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由。也就是说匹配了/payment/get/后，使用uri+Path的访问路径

        - id: payment_routh2 #路由的id，没有限定规则但要求唯一，建议配合服务名
            uri: http://localhost:8001 #匹配后提供服务的路由地址
            predicates:
              - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  client:
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负债均衡
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka