server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka服务器的实例名称
  client:
    register-with-eureka: false #false表示不向中心注册自己
    fetch-registry: false #表示自己端就是注册中心，不用去检查服务
    service-url:
      #设置与euraka server 交互的地址查询服务和注册服务都要依赖这个地址
      defaultZone: http://${euraka.instance.hostname}:${server.port}/eureka/
